version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    open-pull-requests-limit: 5
    groups:
      dev-dependencies:
        patterns:
          - "@types/*"
          - "typescript"
          - "vitest"
          - "eslint*"
          - "prettier"
      production:
        patterns:
          - "*"
        exclude-patterns:
          - "@types/*"
          - "typescript"
          - "vitest"
          - "eslint*"
          - "prettier"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "develop"
