import type { LucideIcon } from 'lucide-react';
import {
  Archive,
  Book,
  Bookmark,
  Briefcase,
  Bug,
  Calendar,
  Camera,
  ClipboardList,
  Cloud,
  Code,
  Cpu,
  Database,
  FileStack,
  FileText,
  Flag,
  FlaskConical,
  Folder,
  GitBranch,
  GitPullRequest,
  Globe,
  Headphones,
  Heart,
  Home,
  Image,
  Inbox,
  Layers,
  Lightbulb,
  Link,
  Lock,
  Mail,
  Map,
  Megaphone,
  MessageSquare,
  Music,
  Package,
  Paperclip,
  Pin,
  Puzzle,
  Rocket,
  Settings,
  Shield,
  SquarePen,
  Star,
  Tag,
  Target,
  Terminal,
  Users,
  Video,
  Wifi,
  Wrench,
  Zap,
} from 'lucide-react';

export const NOTEBOOK_ICON_IDS = [
  'folder',
  'inbox',
  'file-text',
  'file-stack',
  'square-pen',
  'globe',
  'users',
  'lightbulb',
  'megaphone',
  'git-pull-request',
  'settings',
  'rocket',
  'clipboard-list',
  'headphones',
  'git-branch',
  'book',
  'star',
  'heart',
  'code',
  'database',
  'terminal',
  'tag',
  'bookmark',
  'calendar',
  'flag',
  'zap',
  'shield',
  'lock',
  'camera',
  'image',
  'music',
  'video',
  'mail',
  'message-square',
  'map',
  'home',
  'briefcase',
  'layers',
  'package',
  'puzzle',
  'target',
  'wrench',
  'bug',
  'flask-conical',
  'cpu',
  'wifi',
  'cloud',
  'link',
  'paperclip',
  'pin',
  'archive',
] as const;

export type NotebookIconId = (typeof NOTEBOOK_ICON_IDS)[number];

const ICONS: Record<NotebookIconId, LucideIcon> = {
  folder: Folder,
  inbox: Inbox,
  'file-text': FileText,
  'file-stack': FileStack,
  'square-pen': SquarePen,
  globe: Globe,
  users: Users,
  lightbulb: Lightbulb,
  megaphone: Megaphone,
  'git-pull-request': GitPullRequest,
  settings: Settings,
  rocket: Rocket,
  'clipboard-list': ClipboardList,
  headphones: Headphones,
  'git-branch': GitBranch,
  book: Book,
  star: Star,
  heart: Heart,
  code: Code,
  database: Database,
  terminal: Terminal,
  tag: Tag,
  bookmark: Bookmark,
  calendar: Calendar,
  flag: Flag,
  zap: Zap,
  shield: Shield,
  lock: Lock,
  camera: Camera,
  image: Image,
  music: Music,
  video: Video,
  mail: Mail,
  'message-square': MessageSquare,
  map: Map,
  home: Home,
  briefcase: Briefcase,
  layers: Layers,
  package: Package,
  puzzle: Puzzle,
  target: Target,
  wrench: Wrench,
  bug: Bug,
  'flask-conical': FlaskConical,
  cpu: Cpu,
  wifi: Wifi,
  cloud: Cloud,
  link: Link,
  paperclip: Paperclip,
  pin: Pin,
  archive: Archive,
};

export function isNotebookIconId(value: string | null | undefined): value is NotebookIconId {
  return Boolean(value && value in ICONS);
}

export function notebookLucideIcon(
  icon: string | null | undefined,
  fallback: 'inbox' | 'folder' | 'file-stack' = 'folder'
): LucideIcon {
  if (isNotebookIconId(icon)) return ICONS[icon];
  return ICONS[fallback];
}
