import { makePalette, type PaletteSpec } from './themeFactory';

/**
 * First-party palettes that are not GitHub satellites yet.
 * Registered by the Palette Library built-in plugin — not OFFICIAL_THEMES.
 */
export const PALETTE_SPECS: PaletteSpec[] = [
  {
    id: 'dripnex-nord',
    name: 'Nord',
    description: 'Polar night. Frost marks, arctic text.',
    colorScheme: 'dark',
    bg: { base: '#2e3440', surface: '#3b4252', elevated: '#434c5e', inset: '#242933' },
    text: '#eceff4',
    accent: '#88c0d0',
    accentHover: '#8fbcbb',
    status: { active: '#88c0d0', onHold: '#ebcb8b', completed: '#a3be8c', dropped: '#bf616a' },
  },
  {
    id: 'dripnex-snow',
    name: 'Snow',
    description: 'Snow storm paper. Polar Day, frost cyan.',
    colorScheme: 'light',
    bg: { base: '#eceff4', surface: '#e5e9f0', elevated: '#ffffff', inset: '#d8dee9' },
    text: '#2e3440',
    accent: '#5e81ac',
    accentHover: '#4c6d96',
    status: { active: '#5e81ac', onHold: '#d08770', completed: '#a3be8c', dropped: '#bf616a' },
  },
  {
    id: 'dripnex-mocha',
    name: 'Mocha',
    description: 'Catppuccin night. Latte foam on cocoa.',
    colorScheme: 'dark',
    bg: { base: '#1e1e2e', surface: '#181825', elevated: '#313244', inset: '#11111b' },
    text: '#cdd6f4',
    accent: '#cba6f7',
    accentHover: '#f5c2e7',
    status: { active: '#cba6f7', onHold: '#f9e2af', completed: '#a6e3a1', dropped: '#f38ba8' },
  },
  {
    id: 'dripnex-latte',
    name: 'Latte',
    description: 'Catppuccin morning. Warm milk, mauve marks.',
    colorScheme: 'light',
    bg: { base: '#eff1f5', surface: '#e6e9ef', elevated: '#ffffff', inset: '#dce0e8' },
    text: '#4c4f69',
    accent: '#8839ef',
    accentHover: '#7287fd',
    status: { active: '#8839ef', onHold: '#df8e1d', completed: '#40a02b', dropped: '#d20f39' },
  },
  {
    id: 'dripnex-tokyo',
    name: 'Tokyo',
    description: 'Night city. Storm blue on ink.',
    colorScheme: 'dark',
    bg: { base: '#1a1b26', surface: '#16161e', elevated: '#24283b', inset: '#0f0f14' },
    text: '#c0caf5',
    accent: '#7aa2f7',
    accentHover: '#89b4fa',
    status: { active: '#7aa2f7', onHold: '#e0af68', completed: '#9ece6a', dropped: '#f7768e' },
  },
  {
    id: 'dripnex-dracula',
    name: 'Dracula',
    description: 'Classic vampire. Pink on charcoal.',
    colorScheme: 'dark',
    bg: { base: '#282a36', surface: '#21222c', elevated: '#44475a', inset: '#191a21' },
    text: '#f8f8f2',
    accent: '#bd93f9',
    accentHover: '#ff79c6',
    status: { active: '#bd93f9', onHold: '#f1fa8c', completed: '#50fa7b', dropped: '#ff5555' },
  },
  {
    id: 'dripnex-evergreen',
    name: 'Evergreen',
    description: 'Everforest night. Moss on bark.',
    colorScheme: 'dark',
    bg: { base: '#2d353b', surface: '#232a2e', elevated: '#3d484d', inset: '#1e2326' },
    text: '#d3c6aa',
    accent: '#a7c080',
    accentHover: '#83c092',
    status: { active: '#a7c080', onHold: '#dbbc7f', completed: '#83c092', dropped: '#e67e80' },
  },
  {
    id: 'dripnex-grove',
    name: 'Grove',
    description: 'Everforest day. Soft green paper.',
    colorScheme: 'light',
    bg: { base: '#fdf6e3', surface: '#f4f0d9', elevated: '#fffdf4', inset: '#efebd4' },
    text: '#5c6a72',
    accent: '#8da101',
    accentHover: '#3a94c5',
    status: { active: '#8da101', onHold: '#dfa000', completed: '#35a77c', dropped: '#f85552' },
  },
  {
    id: 'dripnex-dawn',
    name: 'Dawn',
    description: 'Rosé morning. Foam, pine, and blush.',
    colorScheme: 'light',
    bg: { base: '#faf4ed', surface: '#fffaf3', elevated: '#fffdfb', inset: '#f2e9e1' },
    text: '#575279',
    accent: '#907aa9',
    accentHover: '#d7827e',
    status: { active: '#907aa9', onHold: '#ea9d34', completed: '#56949f', dropped: '#b4637a' },
  },
  {
    id: 'dripnex-atom',
    name: 'Atom',
    description: 'One Dark. The editor that taught a generation.',
    colorScheme: 'dark',
    bg: { base: '#282c34', surface: '#21252b', elevated: '#2c313c', inset: '#181a1f' },
    text: '#abb2bf',
    accent: '#61afef',
    accentHover: '#c678dd',
    status: { active: '#61afef', onHold: '#e5c07b', completed: '#98c379', dropped: '#e06c75' },
  },
  {
    id: 'dripnex-monokai',
    name: 'Monokai',
    description: 'Sublime classic. Acid green on warm black.',
    colorScheme: 'dark',
    bg: { base: '#272822', surface: '#1e1f1c', elevated: '#3e3d32', inset: '#161713' },
    text: '#f8f8f2',
    accent: '#a6e22e',
    accentHover: '#fd971f',
    status: { active: '#a6e22e', onHold: '#e6db74', completed: '#a6e22e', dropped: '#f92672' },
  },
  {
    id: 'dripnex-ayu',
    name: 'Ayu',
    description: 'Mirage. Gold cursor on deep navy.',
    colorScheme: 'dark',
    bg: { base: '#0d1017', surface: '#0f1419', elevated: '#1c2328', inset: '#0a0d12' },
    text: '#bfbdb6',
    accent: '#ffb454',
    accentHover: '#ff8f40',
    status: { active: '#ffb454', onHold: '#e6b673', completed: '#7fd962', dropped: '#f07178' },
  },
  {
    id: 'dripnex-flexoki',
    name: 'Flexoki',
    description: 'Inkwell paper. Warm black, ceramic teal.',
    colorScheme: 'dark',
    bg: { base: '#100f0f', surface: '#1c1b1a', elevated: '#282726', inset: '#0d0c0c' },
    text: '#cecdc3',
    accent: '#3aa99f',
    accentHover: '#4385be',
    status: { active: '#3aa99f', onHold: '#d0a215', completed: '#879a39', dropped: '#d14d41' },
  },
  {
    id: 'dripnex-graphite',
    name: 'Graphite',
    description: 'Pencil gray. No hue, just pressure.',
    colorScheme: 'dark',
    bg: { base: '#1c1c1c', surface: '#141414', elevated: '#2a2a2a', inset: '#101010' },
    text: '#e8e8e8',
    accent: '#a3a3a3',
    accentHover: '#d4d4d4',
    status: { active: '#a3a3a3', onHold: '#c4c4c4', completed: '#8a8a8a', dropped: '#6b6b6b' },
  },
  {
    id: 'dripnex-void',
    name: 'Void',
    description: 'True black. OLED, one silver mark.',
    colorScheme: 'dark',
    bg: { base: '#000000', surface: '#0a0a0a', elevated: '#141414', inset: '#000000' },
    text: '#e4e4e7',
    accent: '#e4e4e7',
    accentHover: '#ffffff',
    status: { active: '#e4e4e7', onHold: '#a1a1aa', completed: '#d4d4d8', dropped: '#71717a' },
  },
  {
    id: 'dripnex-cobalt',
    name: 'Cobalt',
    description: 'Deep studio blue. The old IDE night.',
    colorScheme: 'dark',
    bg: { base: '#002240', surface: '#001b33', elevated: '#003056', inset: '#001429' },
    text: '#ffffff',
    accent: '#ff9d00',
    accentHover: '#ffc66d',
    status: { active: '#ff9d00', onHold: '#ffc66d', completed: '#3ad900', dropped: '#ff628c' },
  },
];

export const PALETTE_LIBRARY = PALETTE_SPECS.map(makePalette);
