import type { CommandDefinition } from '../types';

export const appCommands: CommandDefinition[] = [
  {
    id: 'app:new-note',
    name: 'New Note',
    category: 'note',
    context: 'app',
    defaultKeybinding: { key: 'n', modifiers: ['Mod'] },
    icon: 'Plus',
    showInPalette: true,
  },
  {
    id: 'app:duplicate-note',
    name: 'Duplicate Note',
    category: 'note',
    context: 'app',
    defaultKeybinding: { key: 'd', modifiers: ['Mod'] },
    icon: 'Copy',
    showInPalette: true,
  },
  {
    id: 'app:focus-search',
    name: 'Focus Search',
    category: 'navigation',
    context: 'app',
    defaultKeybinding: { key: 'f', modifiers: ['Mod'] },
    icon: 'Search',
    showInPalette: true,
  },
  {
    id: 'app:cycle-view-mode',
    name: 'Cycle View Mode',
    category: 'view',
    context: 'app',
    defaultKeybinding: { key: 'p', modifiers: ['Mod', 'Shift'] },
    icon: 'Columns',
    showInPalette: true,
  },
  {
    id: 'app:toggle-graph',
    name: 'Toggle Graph View',
    category: 'view',
    context: 'app',
    defaultKeybinding: { key: 'g', modifiers: ['Mod'] },
    icon: 'Share2',
    showInPalette: true,
  },
  {
    id: 'app:open-settings',
    name: 'Open Settings',
    category: 'app',
    context: 'app',
    defaultKeybinding: { key: ',', modifiers: ['Mod'] },
    icon: 'Settings',
    showInPalette: true,
  },
  {
    id: 'app:command-palette',
    name: 'Command Palette',
    category: 'app',
    context: 'app',
    defaultKeybinding: { key: 'p', modifiers: ['Mod'] },
    icon: 'Terminal',
    showInPalette: false,
  },
];
