import type { CommandDefinition } from '../types';

export const appCommands: CommandDefinition[] = [
  {
    id: 'app:open-note',
    name: 'Open Note',
    category: 'note',
    context: 'app',
    icon: 'FileText',
    showInPalette: false,
  },
  {
    id: 'app:new-note',
    name: 'New Note',
    category: 'note',
    context: 'app',
    defaultKeybinding: { key: 'n', modifiers: ['Mod'] },
    icon: 'Plus',
    showInPalette: true,
  },
  {
    id: 'app:duplicate-note',
    name: 'Duplicate Note',
    category: 'note',
    context: 'app',
    defaultKeybinding: { key: 'd', modifiers: ['Mod'] },
    icon: 'Copy',
    showInPalette: true,
  },
  {
    id: 'app:focus-search',
    name: 'Search Notes',
    category: 'navigation',
    context: 'app',
    defaultKeybinding: { key: 'f', modifiers: ['Mod', 'Shift'] },
    icon: 'Search',
    showInPalette: true,
  },
  {
    id: 'app:find-in-note',
    name: 'Find in Note',
    category: 'navigation',
    context: 'app',
    defaultKeybinding: { key: 'f', modifiers: ['Mod'] },
    icon: 'Search',
    showInPalette: true,
  },
  {
    id: 'app:cycle-view-mode',
    name: 'Cycle View Mode',
    category: 'view',
    context: 'app',
    defaultKeybinding: { key: 'p', modifiers: ['Mod', 'Shift'] },
    icon: 'Columns',
    showInPalette: true,
  },
  {
    id: 'app:toggle-preview',
    name: 'Toggle Preview',
    category: 'view',
    context: 'app',
    icon: 'Eye',
    showInPalette: true,
  },
  {
    id: 'app:toggle-split',
    name: 'Toggle Split View',
    category: 'view',
    context: 'app',
    icon: 'Columns2',
    showInPalette: true,
  },
  {
    id: 'app:next-note',
    name: 'Next Note',
    category: 'navigation',
    context: 'note-list',
    defaultKeybinding: { key: 'j', modifiers: [] },
    icon: 'ChevronDown',
    showInPalette: true,
  },
  {
    id: 'app:prev-note',
    name: 'Previous Note',
    category: 'navigation',
    context: 'note-list',
    defaultKeybinding: { key: 'k', modifiers: [] },
    icon: 'ChevronUp',
    showInPalette: true,
  },
  {
    id: 'app:save-note',
    name: 'Save Note',
    category: 'note',
    context: 'app',
    defaultKeybinding: { key: 's', modifiers: ['Mod'] },
    icon: 'Save',
    showInPalette: true,
  },
  {
    id: 'app:note-back',
    name: 'Back',
    category: 'navigation',
    context: 'app',
    defaultKeybinding: { key: '[', modifiers: ['Mod'] },
    icon: 'ArrowLeft',
    showInPalette: true,
  },
  {
    id: 'app:note-forward',
    name: 'Forward',
    category: 'navigation',
    context: 'app',
    defaultKeybinding: { key: ']', modifiers: ['Mod'] },
    icon: 'ArrowRight',
    showInPalette: true,
  },
  {
    id: 'app:toggle-zen',
    name: 'Toggle Distraction Free Mode',
    category: 'view',
    context: 'app',
    icon: 'Maximize2',
    showInPalette: true,
  },
  {
    id: 'app:open-in-window',
    name: 'Open in New Window',
    category: 'note',
    context: 'app',
    icon: 'SquareArrowOutUpRight',
    showInPalette: true,
  },
  {
    id: 'app:toggle-outline',
    name: 'Toggle Outline',
    category: 'view',
    context: 'app',
    icon: 'Hash',
    showInPalette: true,
  },
  {
    id: 'app:toggle-graph',
    name: 'Toggle Graph View',
    category: 'view',
    context: 'app',
    defaultKeybinding: { key: 'g', modifiers: ['Mod'] },
    icon: 'Share2',
    showInPalette: true,
  },
  {
    id: 'app:open-settings',
    name: 'Open Settings',
    category: 'app',
    context: 'app',
    defaultKeybinding: { key: ',', modifiers: ['Mod'] },
    icon: 'Settings',
    showInPalette: true,
  },
  {
    id: 'app:command-palette',
    name: 'Command Palette',
    category: 'app',
    context: 'app',
    defaultKeybinding: { key: 'p', modifiers: ['Mod'] },
    icon: 'Terminal',
    showInPalette: false,
  },
  {
    id: 'app:quick-open',
    name: 'Quick Open',
    category: 'navigation',
    context: 'app',
    defaultKeybinding: { key: 'o', modifiers: ['Mod'] },
    icon: 'FileText',
    showInPalette: true,
  },
  {
    id: 'app:jump-notebook',
    name: 'Jump to Notebook',
    category: 'navigation',
    context: 'app',
    defaultKeybinding: { key: 'o', modifiers: ['Mod', 'Shift'] },
    icon: 'BookMarked',
    showInPalette: true,
  },
  {
    id: 'app:jump-tag',
    name: 'Jump to Tag',
    category: 'navigation',
    context: 'app',
    defaultKeybinding: { key: 't', modifiers: ['Mod', 'Shift'] },
    icon: 'Hash',
    showInPalette: true,
  },
  {
    id: 'app:jump-heading',
    name: 'Jump to Heading',
    category: 'navigation',
    context: 'app',
    defaultKeybinding: { key: 'h', modifiers: ['Mod', 'Shift'] },
    icon: 'Hash',
    showInPalette: true,
  },
  {
    id: 'app:copy-wikilink',
    name: 'Copy Wikilink',
    category: 'note',
    context: 'app',
    icon: 'Link',
    showInPalette: true,
  },
  {
    id: 'app:open-now-board',
    name: 'Open Living Board',
    category: 'navigation',
    context: 'app',
    icon: 'FileText',
    showInPalette: true,
  },
  {
    id: 'app:open-init-script',
    name: 'Open Init Script',
    category: 'plugin',
    context: 'app',
    icon: 'FileCode',
    showInPalette: true,
  },
  {
    id: 'app:open-user-styles',
    name: 'Open User Stylesheet',
    category: 'plugin',
    context: 'app',
    icon: 'Palette',
    showInPalette: true,
  },
  {
    id: 'app:open-keymap',
    name: 'Open Keymap',
    category: 'plugin',
    context: 'app',
    icon: 'Keyboard',
    showInPalette: true,
  },
  {
    id: 'app:reload-plugins',
    name: 'Reload Plugins',
    category: 'plugin',
    context: 'app',
    defaultKeybinding: { key: 'r', modifiers: ['Mod', 'Alt'] },
    icon: 'RefreshCw',
    showInPalette: true,
  },
];
