import type { CommandDefinition } from '../types';

export const editorCommands: CommandDefinition[] = [
  {
    id: 'editor:toggle-bold',
    name: 'Toggle Bold',
    category: 'editor',
    context: 'editor',
    defaultKeybinding: { key: 'b', modifiers: ['Mod'] },
    icon: 'Bold',
    showInPalette: true,
  },
  {
    id: 'editor:toggle-italic',
    name: 'Toggle Italic',
    category: 'editor',
    context: 'editor',
    defaultKeybinding: { key: 'i', modifiers: ['Mod'] },
    icon: 'Italic',
    showInPalette: true,
  },
  {
    id: 'editor:toggle-strikethrough',
    name: 'Toggle Strikethrough',
    category: 'editor',
    context: 'editor',
    icon: 'Strikethrough',
    showInPalette: true,
  },
  {
    id: 'editor:toggle-inline-code',
    name: 'Toggle Inline Code',
    category: 'editor',
    context: 'editor',
    defaultKeybinding: { key: 'e', modifiers: ['Mod'] },
    icon: 'Code',
    showInPalette: true,
  },
  {
    id: 'editor:insert-link',
    name: 'Insert Link',
    category: 'editor',
    context: 'editor',
    defaultKeybinding: { key: 'k', modifiers: ['Mod', 'Shift'] },
    icon: 'Link',
    showInPalette: true,
  },
  {
    id: 'editor:insert-heading',
    name: 'Insert Heading',
    category: 'editor',
    context: 'editor',
    icon: 'Heading2',
    showInPalette: true,
  },
  {
    id: 'editor:insert-unordered-list',
    name: 'Insert Bullet List',
    category: 'editor',
    context: 'editor',
    icon: 'List',
    showInPalette: true,
  },
  {
    id: 'editor:insert-ordered-list',
    name: 'Insert Numbered List',
    category: 'editor',
    context: 'editor',
    icon: 'ListOrdered',
    showInPalette: true,
  },
  {
    id: 'editor:insert-checkbox',
    name: 'Insert Checkbox',
    category: 'editor',
    context: 'editor',
    icon: 'CheckSquare',
    showInPalette: true,
  },
  {
    id: 'editor:insert-quote',
    name: 'Insert Quote',
    category: 'editor',
    context: 'editor',
    icon: 'Quote',
    showInPalette: true,
  },
  {
    id: 'editor:insert-code-block',
    name: 'Insert Code Block',
    category: 'editor',
    context: 'editor',
    icon: 'FileCode',
    showInPalette: true,
  },
  {
    id: 'editor:insert-horizontal-rule',
    name: 'Insert Horizontal Rule',
    category: 'editor',
    context: 'editor',
    icon: 'Minus',
    showInPalette: true,
  },
  {
    id: 'editor:find',
    name: 'Find in Note',
    category: 'editor',
    context: 'editor',
    defaultKeybinding: { key: 'f', modifiers: ['Mod'] },
    icon: 'Search',
    showInPalette: true,
  },
  {
    id: 'editor:find-next',
    name: 'Find Next',
    category: 'editor',
    context: 'editor',
    icon: 'ChevronDown',
    showInPalette: true,
  },
  {
    id: 'editor:find-previous',
    name: 'Find Previous',
    category: 'editor',
    context: 'editor',
    icon: 'ChevronUp',
    showInPalette: true,
  },
  {
    id: 'editor:toggle-fold',
    name: 'Toggle Fold',
    category: 'editor',
    context: 'editor',
    icon: 'ChevronsDownUp',
    showInPalette: true,
  },
  {
    id: 'editor:fold-all',
    name: 'Fold All Headings',
    category: 'editor',
    context: 'editor',
    icon: 'ChevronsUp',
    showInPalette: true,
  },
  {
    id: 'editor:unfold-all',
    name: 'Unfold All',
    category: 'editor',
    context: 'editor',
    icon: 'ChevronsDown',
    showInPalette: true,
  },
  {
    id: 'editor:follow-link',
    name: 'Follow Link',
    category: 'editor',
    context: 'editor',
    defaultKeybinding: { key: 'Enter', modifiers: ['Mod', 'Shift'] },
    icon: 'Link',
    showInPalette: true,
  },
  {
    id: 'editor:undo',
    name: 'Undo',
    category: 'editor:history',
    context: 'editor',
    defaultKeybinding: { key: 'z', modifiers: ['Mod'] },
    icon: 'Undo2',
    showInPalette: true,
  },
  {
    id: 'editor:redo',
    name: 'Redo',
    category: 'editor:history',
    context: 'editor',
    defaultKeybinding: { key: 'z', modifiers: ['Mod', 'Shift'] },
    icon: 'Redo2',
    showInPalette: true,
  },
  {
    id: 'editor:edit-with-ai',
    name: 'Edit with AI',
    category: 'editor',
    context: 'editor',
    defaultKeybinding: { key: 'Enter', modifiers: ['Mod'] },
    icon: 'PenLine',
    showInPalette: true,
  },
  {
    id: 'editor:trigger-nes',
    name: 'Suggest Next Edit',
    category: 'editor',
    context: 'editor',
    defaultKeybinding: { key: '\\', modifiers: ['Alt'] },
    icon: 'Sparkles',
    showInPalette: true,
  },
  {
    id: 'editor:accept-nes',
    name: 'Accept Next Edit',
    category: 'editor',
    context: 'editor',
    showInPalette: false,
  },
  {
    id: 'editor:dismiss-nes',
    name: 'Dismiss Next Edit',
    category: 'editor',
    context: 'editor',
    showInPalette: false,
  },
  {
    id: 'editor:copy-line-up',
    name: 'Copy Line Up',
    category: 'editor',
    context: 'editor',
    defaultKeybinding: { key: 'arrowup', modifiers: ['Shift', 'Alt'] },
    showInPalette: true,
  },
  {
    id: 'editor:copy-line-down',
    name: 'Copy Line Down',
    category: 'editor',
    context: 'editor',
    defaultKeybinding: { key: 'arrowdown', modifiers: ['Shift', 'Alt'] },
    showInPalette: true,
  },
  {
    id: 'editor:move-line-up',
    name: 'Move Line Up',
    category: 'editor',
    context: 'editor',
    defaultKeybinding: { key: 'arrowup', modifiers: ['Alt'] },
    showInPalette: true,
  },
  {
    id: 'editor:move-line-down',
    name: 'Move Line Down',
    category: 'editor',
    context: 'editor',
    defaultKeybinding: { key: 'arrowdown', modifiers: ['Alt'] },
    showInPalette: true,
  },
  {
    id: 'editor:insert-blank-line',
    name: 'Insert Blank Line Below',
    category: 'editor',
    context: 'editor',
    showInPalette: true,
  },
  {
    id: 'editor:insert-line-before',
    name: 'Insert Blank Line Above',
    category: 'editor',
    context: 'editor',
    showInPalette: true,
  },
  {
    id: 'editor:select-line',
    name: 'Select Line',
    category: 'editor',
    context: 'editor',
    defaultKeybinding: { key: 'l', modifiers: ['Mod'] },
    showInPalette: true,
  },
  {
    id: 'editor:go-matching-bracket',
    name: 'Go to Matching Bracket',
    category: 'editor',
    context: 'editor',
    showInPalette: true,
  },
  {
    id: 'editor:select-matching-bracket',
    name: 'Select Matching Bracket',
    category: 'editor',
    context: 'editor',
    showInPalette: true,
  },
  {
    id: 'editor:select-parent-syntax',
    name: 'Select Parent Syntax',
    category: 'editor',
    context: 'editor',
    showInPalette: true,
  },
  {
    id: 'editor:go-subword-left',
    name: 'Go Subword Left',
    category: 'editor',
    context: 'editor',
    showInPalette: true,
  },
  {
    id: 'editor:go-subword-right',
    name: 'Go Subword Right',
    category: 'editor',
    context: 'editor',
    showInPalette: true,
  },
  {
    id: 'editor:select-subword-left',
    name: 'Select Subword Left',
    category: 'editor',
    context: 'editor',
    showInPalette: true,
  },
  {
    id: 'editor:select-subword-right',
    name: 'Select Subword Right',
    category: 'editor',
    context: 'editor',
    showInPalette: true,
  },
  {
    id: 'editor:select-next-occurrence',
    name: 'Select Next Occurrence',
    category: 'editor',
    context: 'editor',
    showInPalette: true,
  },
  {
    id: 'editor:select-selection-matches',
    name: 'Select All Occurrences',
    category: 'editor',
    context: 'editor',
    defaultKeybinding: { key: 'f3', modifiers: ['Alt'] },
    showInPalette: true,
  },
  {
    id: 'editor:toggle-comment',
    name: 'Toggle Comment',
    category: 'editor',
    context: 'editor',
    defaultKeybinding: { key: '/', modifiers: ['Mod'] },
    showInPalette: true,
  },
  {
    id: 'editor:toggle-line-comment',
    name: 'Toggle Line Comment',
    category: 'editor',
    context: 'editor',
    showInPalette: true,
  },
  {
    id: 'editor:sort-lines-insensitive',
    name: 'Sort Lines',
    category: 'editor',
    context: 'editor',
    showInPalette: true,
  },
  {
    id: 'editor:reverse-sort-lines-insensitive',
    name: 'Sort Lines Reverse',
    category: 'editor',
    context: 'editor',
    showInPalette: true,
  },
  {
    id: 'editor:sort-lines',
    name: 'Sort Lines (Case Sensitive)',
    category: 'editor',
    context: 'editor',
    showInPalette: true,
  },
  {
    id: 'editor:reverse-sort-lines',
    name: 'Sort Lines Reverse (Case Sensitive)',
    category: 'editor',
    context: 'editor',
    showInPalette: true,
  },
  {
    id: 'editor:join-lines',
    name: 'Join Lines',
    category: 'editor',
    context: 'editor',
    showInPalette: true,
  },
  {
    id: 'editor:upcase-at-cursor',
    name: 'Uppercase',
    category: 'editor',
    context: 'editor',
    showInPalette: true,
  },
  {
    id: 'editor:downcase-at-cursor',
    name: 'Lowercase',
    category: 'editor',
    context: 'editor',
    showInPalette: true,
  },
  {
    id: 'editor:find-under',
    name: 'Find Under',
    category: 'editor',
    context: 'editor',
    defaultKeybinding: { key: 'f3', modifiers: ['Mod'] },
    showInPalette: true,
  },
  {
    id: 'editor:find-under-previous',
    name: 'Find Under Previous',
    category: 'editor',
    context: 'editor',
    defaultKeybinding: { key: 'f3', modifiers: ['Mod', 'Shift'] },
    showInPalette: true,
  },
  {
    id: 'editor:skip-and-select-next-occurrence',
    name: 'Skip and Select Next Occurrence',
    category: 'editor',
    context: 'editor',
    showInPalette: true,
  },
  {
    id: 'editor:split-selection-by-line',
    name: 'Split Selection by Line',
    category: 'editor',
    context: 'editor',
    showInPalette: true,
  },
  {
    id: 'editor:scroll-line-up',
    name: 'Scroll Line Up',
    category: 'editor',
    context: 'editor',
    showInPalette: true,
  },
  {
    id: 'editor:scroll-line-down',
    name: 'Scroll Line Down',
    category: 'editor',
    context: 'editor',
    showInPalette: true,
  },
  {
    id: 'editor:show-in-center',
    name: 'Scroll Cursor to Center',
    category: 'editor',
    context: 'editor',
    showInPalette: true,
  },
];
