import { useState, useEffect, useCallback, useMemo, useRef } from 'react';
import { useCssVariables, usePluginStyles, useThemeOverrides } from '@dripnex/plugin-api';
import { scanMarkdown } from '@dripnex/markdown';
import type { NoteSnapshot } from '../preload/index';
import { UpdateBanner } from './components/UpdateBanner';
import { NoteList } from './components/NoteList';
import { NoteEditor } from './components/NoteEditor';
import { NoteWindow } from './components/NoteWindow';
import { Sidebar } from './components/sidebar';
import { GraphView } from './components/GraphView';
import { CommandPalette } from './components/CommandPalette';
import { ConflictResolver } from './components/sync/ConflictResolver';
import { AiPanel } from './components/ai/AiPanel';
import { LicenseProvider } from './contexts/LicenseContext';
import { ToastProvider } from './components/Toast';
import { Toaster } from './ui/primitives';
import { Welcome } from './components/Welcome';
import { AuthGate } from './components/auth/AuthGate';
import { useAuthStore, selectIsAuthenticated, selectSessionHydrated } from './stores/authStore';
import { resolveAppShell } from './utils/appShell';
import { ErrorBoundary } from './components/ErrorBoundary';
